#!/bin/bash

if [ -f "/c/Program Files/CMake/bin/cmake.exe" ]; then
	BINOC_CMAKE_PATH="/c/Program Files/CMake/bin/cmake.exe"
elif [ -f "/c/Program Files (x86)/CMake/bin/cmake.exe" ]; then
	BINOC_CMAKE_PATH="/c/Program Files (x86)/CMake/bin/cmake.exe"	
else
	echo Building requires CMake as well as a few other tools. This script also only works on Windows so Linux users will have to do it manually.
	echo This MAY be resolved in the future... I doubt it though.
	exit 1
fi

if [ -d ./obj-dir ]; then
	rm -rf ./obj-dir
fi

if [ -d ./obj-dir ]; then
	echo Previous obj-dir did not get purged. Please remove it manually.
	exit 1
fi

mkdir obj-dir

cd obj-dir

"$BINOC_CMAKE_PATH" ../ -G "Unix Makefiles"

"$BINOC_CMAKE_PATH" --build ./

cd ..